version: '3.8'

services:
  microservicio7:
    image: microservicio7:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8131:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql7

  mysql7:
    image: mysql:8.0
    ports:
      - "3317:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P4ssword!
      MYSQL_DATABASE: my-app